"""fixed typo in orders table

Revision ID: ac55f841d712
Revises: 3879ddfb980a
Create Date: 2026-06-11 18:36:14.392540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac55f841d712'
down_revision: Union[str, Sequence[str], None] = '3879ddfb980a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('estimated_hours', sa.Numeric(precision=6, scale=2), nullable=False))
    op.drop_column('orders', 'esimated_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('esimated_hours', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.drop_column('orders', 'estimated_hours')
    # ### end Alembic commands ###
